### ISSUE TITLE
Can I update extensions via cli ?

### ISSUE THREAD

**Issue by toleabivol** [ThemeFuse/Unyson-CLI#8]
Is there a command for updating extensions ?

**Comment by ViorelEremia** [comment]
Can you test that?

**Comment by toleabivol** [comment]
might be a different issue but that's what I get now when trying to install the wp cli extension for Unyson-CLI

```
wp package install ThemeFuse/Unyson-CLI
Installing package ThemeFuse/Unyson-CLI (dev-master)
Updating /home/bivol/.wp-cli/packages/composer.json to require the package...
Registering git@github.com:ThemeFuse/Unyson-CLI.git as a VCS repository...
Using Composer to install the package...
---
Loading composer repositories with package information
Updating dependencies
Resolving dependencies through SAT
Dependency resolution completed in 0.119 seconds
Your requirements could not be resolved to an installable set of packages.
Problem 1
    - The requested package themefuse/unyson-cli could not be found in any version, there may be a typo in the package name.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see https://getcomposer.org/doc/04-schema.md#minimum-stability for more details.

Read https://getcomposer.org/doc/articles/troubleshooting.md for further common problems.
Running update with --no-dev does not mean require-dev is ignored, it just means the packages will not be installed. If dev requirements are blocking the update you have to resolve those problems.
---
Error: Package installation failed (Composer return code 2). Reverted composer.json
```

**Comment by ViorelEremia** [comment]
use ```wp package install git@github.com:ThemeFuse/Unyson-CLI.git```

**Comment by toleabivol** [comment]
That worked. Now the test with the extensions is failing with following trace :

```
wp unyson exts update
PHP Fatal error:  Uncaught Error: Call to a member function get_extensions_with_updates() on null in /home/bivol/.wp-cli/packages/vendor/themefuse/unyson/src/Commands/Extensions.php:192
Stack trace:
#0 [internal function]: Unyson\Commands\Extensions->update(Array, Array)
#1 phar:///usr/local/bin/wp/php/WP_CLI/Dispatcher/CommandFactory.php(87): call_user_func(Array, Array, Array)
#2 [internal function]: WP_CLI\Dispatcher\CommandFactory::WP_CLI\Dispatcher\{closure}(Array, Array)
#3 phar:///usr/local/bin/wp/php/WP_CLI/Dispatcher/Subcommand.php(421): call_user_func(Object(Closure), Array, Array)
#4 phar:///usr/local/bin/wp/php/WP_CLI/Runner.php(336): WP_CLI\Dispatcher\Subcommand->invoke(Array, Array, Array)
#5 phar:///usr/local/bin/wp/php/WP_CLI/Runner.php(343): WP_CLI\Runner->run_command(Array, Array)
#6 phar:///usr/local/bin/wp/php/WP_CLI/Runner.php(1034): WP_CLI\Runner->_run_command_and_exit()
#7 phar:///usr/local/bin/wp/php/WP_CLI/Bootstrap/LaunchRunner.php(23): WP_CLI\Runner->start()
#8 phar:///usr/local/bin/wp/php/bootstrap. in /home/bivol/.wp-cli/packages/vendor/themefuse/unyson/src/Commands/Extensions.php on line 192
Fatal error: Uncaught Error: Call to a member function get_extensions_with_updates() on null in /home/bivol/.wp-cli/packages/vendor/themefuse/unyson/src/Commands/Extensions.php:192
Stack trace:
#0 [internal function]: Unyson\Commands\Extensions->update(Array, Array)
#1 phar:///usr/local/bin/wp/php/WP_CLI/Dispatcher/CommandFactory.php(87): call_user_func(Array, Array, Array)
#2 [internal function]: WP_CLI\Dispatcher\CommandFactory::WP_CLI\Dispatcher\{closure}(Array, Array)
#3 phar:///usr/local/bin/wp/php/WP_CLI/Dispatcher/Subcommand.php(421): call_user_func(Object(Closure), Array, Array)
#4 phar:///usr/local/bin/wp/php/WP_CLI/Runner.php(336): WP_CLI\Dispatcher\Subcommand->invoke(Array, Array, Array)
#5 phar:///usr/local/bin/wp/php/WP_CLI/Runner.php(343): WP_CLI\Runner->run_command(Array, Array)
#6 phar:///usr/local/bin/wp/php/WP_CLI/Runner.php(1034): WP_CLI\Runner->_run_command_and_exit()
#7 phar:///usr/local/bin/wp/php/WP_CLI/Bootstrap/LaunchRunner.php(23): WP_CLI\Runner->start()
#8 phar:///usr/local/bin/wp/php/bootstrap. in /home/bivol/.wp-cli/packages/vendor/themefuse/unyson/src/Commands/Extensions.php on line 192
```

**Comment by ViorelEremia** [comment]
clone github unyson i related that commit here: https://github.com/ThemeFuse/Unyson/commit/ce537f1a2abea26ecd10b0257d516efc230a74ad

**Comment by ViorelEremia** [comment]
In next upate of unyson that will be availabele

**Comment by toleabivol** [comment]
This error still happens with 2.7.12
